from typing import List

class NetworkTable:
    def getKeys(self) -> List[str]: ...
    def getPath(self) -> str: ...

    def getBoolean(self, key: str, defaultValue: bool) -> bool: ...
    def getNumber(self, key: str, defaultValue: float) -> float: ...
    def getString(self, key: str, defaultValue: str) -> str: ...
    def getRaw(self, key: str, defaultValue: str) -> str: ...
    def getBooleanArray(self, key: str, defaultValue: List[bool]) -> List[bool]: ...
    def getNumberArray(self, key: str, defaultValue: List[float]) -> List[float]: ...
    def getStringArray(self, key: str, defaultValue: List[str]) -> List[str]: ...

    def putBoolean(self, key: str, value: bool) -> bool: ...
    def putNumber(self, key: str, value: float) -> bool: ...
    def putString(self, key: str, value: str) -> bool: ...
    def putRaw(self, key: str, value: str) -> bool: ...
    def putBooleanArray(self, key: str, value: List[bool]) -> bool: ...
    def putNumberArray(self, key: str, value: List[float]) -> bool: ...
    def putStringArray(self, key: str, value: List[str]) -> bool: ...
